### ISSUE TITLE
Keen.io plugin

### ISSUE THREAD

**Issue by lvivier** [Retsly/log#30]
- [ ] add a keen.io plugin
- [ ] remove keen.io stuff from retsly/api

Should work the same as in retsly/api but be made more generic to accommodate www, pub, etc.

**Comment by RongxinZhang** [comment]
Referencing main brief: https://github.com/Retsly/log/issues/39

**Comment by slajax** [comment]
@RongxinZhang I think we can close this since there is no keen plugin anymore, it'll all go through segment.

**Comment by RongxinZhang** [comment]
@slajax Agreed.
